### ISSUE TITLE
security issues

### ISSUE THREAD

**Issue by Kidel** [iangray001/esp8266-wakeonlan#1]
Allowing to pick the target ip address from the web may not be a good idea. 
I've made a fork where I added a password, allowed for only 3-digit numbers to be added as final ip byte (to pick the broadcast) and I also added many delays. This should overall make it more difficult to use people's WOL devices as a botnet to do DDoS. 

I've also updated the instructions and added an Arduino IDE version. Please tell me if you're interested in a pull request.

**Comment by iangray001** [comment]
That sounds like a good idea, and good point about the DDoS issue. In this day and age we should all be aware of that! Send a PR please.

**Comment by Kidel** [comment]
Done :)

**Comment by iangray001** [comment]
Thanks.
